apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo1
  namespace: wego-system
resources:
- ../../../apps/demo1
- ../../../apps/Yet Another Demo
- ../../../apps/demo2
- ../../../apps/demo2
